changed "blaze" to "cyclone" Also added lib path to the docker run command at end of script

diff --git a/lrose-docker-scripts/lrose b/lrose-docker-scripts/lrose
--- a/lrose-docker-scripts/lrose
+++ b/lrose-docker-scripts/lrose
@@ -9,35 +9,35 @@ my_version=1.01
 # You do
 # lrose <few options listed below> -- <cmd> <cmd options>
 #
-# By default, the image is lrose-blaze and the container is lrose-container
+# By default, the image is lrose-cyclone and the container is lrose-container
 
 print_help() {
     echo "lrose wrapper version $my_version"
     echo "usage: lrose [args] -- command [command args]"
     cat <<EOF
 
-    -a|--argfile <file>		Specify a file that has additional options (default ~/.lroseargs)
-    		 		The file has one entry per line with #, =, --, and : serving as keywords
-    		 			# denotes a comment
-					= Is used to specify an environment variable
-					     foo=bar gets translated to -e foo=bar
-					: Is used to specify a volume mapping
-					     /from:/to gets translated to -v /from:/to
+    -a|--argfile <file>     Specify a file that has additional options (default ~/.lroseargs)
+                    The file has one entry per line with #, =, --, and : serving as keywords
+                        # denotes a comment
+                    = Is used to specify an environment variable
+                         foo=bar gets translated to -e foo=bar
+                    : Is used to specify a volume mapping
+                         /from:/to gets translated to -v /from:/to
                                        -- Denotes a raw argument
                                              --whatever will be passed as is
 
-    -h|--help			Print help and exit 
-    -c|--container <name>	Use this container instead of the default lrose-container 
-    -d|--debug			Print debug info 
-    -i|--image <name>		Use this image instead of the default lrose-image 
-    -n|--no			Don't run the command (useful with -d) 
-    -r|--remove			Remove the container when done 
-    -v|--volume <from:to>	Add volume mappings. You can have several -v options 
-    				    from is your local host absolute path 
-				    to is the absolute path inside the container.
+    -h|--help           Print help and exit 
+    -c|--container <name>   Use this container instead of the default lrose-container 
+    -d|--debug          Print debug info 
+    -i|--image <name>       Use this image instead of the default lrose-image 
+    -n|--no         Don't run the command (useful with -d) 
+    -r|--remove         Remove the container when done 
+    -v|--volume <from:to>   Add volume mappings. You can have several -v options 
+                        from is your local host absolute path 
+                    to is the absolute path inside the container.
 
-    command [command args] is the lrose-blaze command invocation. For example
-    	    HawkEye -archive_url /tmp/KHGX -start_time "2017 08 00 00 00" -time_span 7200
+    command [command args] is the lrose-cyclone command invocation. For example
+            HawkEye -archive_url /tmp/KHGX -start_time "2017 08 00 00 00" -time_span 7200
 
 EOF
 }
@@ -52,12 +52,12 @@ run_cmd() {
     cmd="$1"
     shift
     if [ "$verbose" -eq 1 ]; then
-	echo "cmd: $cmd $@"
+    echo "cmd: $cmd $@"
     fi
 
     if [ "$run" -eq 1 ]; then
-	result="$($cmd "$@")"
-	echo "$result"
+    result="$($cmd "$@")"
+    echo "$result"
     fi
 }
 
@@ -67,7 +67,7 @@ print_msg() {
     debug=$1
     shift
     if [ "$debug" -eq 1 ]; then
-	echo "$@"
+    echo "$@"
     fi
 }
 
@@ -82,7 +82,7 @@ container_status() {
 # A few default values that can be overwritten on the command line
 
 REMOVE="--rm"
-IMAGE=`docker images | grep nsflrose/lrose-blaze | grep latest | awk '{ print $3; }'`
+IMAGE=`docker images | grep nsflrose/lrose-cyclone | grep latest | awk '{ print $3; }'`
 CONTAINER="lrose-container"
 ARG_FILE="$HOME/.lroseargs"
 VOLUME_ARGS="-v $HOME:$HOME"
@@ -102,19 +102,19 @@ my_gid=`id -g`
 my_os=`uname`
 case $my_os in
     Linux)
-	DISPLAY_OPT="--env=DISPLAY --env QT_X11_NO_MITSHM=1"
-	;;	
+    DISPLAY_OPT="--env=DISPLAY --env QT_X11_NO_MITSHM=1"
+    ;;  
     Darwin)
-	my_host=`hostname`
-	my_ip=`host $my_host`
-	my_ip=${my_ip##* }
-	DISPLAY_OPT="-e DISPLAY=$my_ip:0"
-	xhost +$my_ip > /dev/null
+    my_host=`hostname`
+    my_ip=`host $my_host`
+    my_ip=${my_ip##* }
+    DISPLAY_OPT="-e DISPLAY=$my_ip:0"
+    xhost +$my_ip > /dev/null
     ;;
     *)
-	echo "Unknown OS '$my_os'. I don't know how to set up DISPLAY. Using Linux"
-	DISPLAY_OPT="--env=\"DISPLAY\" --env QT_X11_NO_MITSHM=1"
-	;;
+    echo "Unknown OS '$my_os'. I don't know how to set up DISPLAY. Using Linux"
+    DISPLAY_OPT="--env=\"DISPLAY\" --env QT_X11_NO_MITSHM=1"
+    ;;
 esac
 
 # Process options
@@ -123,51 +123,51 @@ while [[ $# -gt 0 ]]
 do
     key="$1"
     case $key in
-	-a|--argfile)
-	    ARG_FILE="$2"
-	    shift # past argument
-	    shift # past value
-	    ;;
-	-h|--help)
-	    print_help
-	    exit 0
-	    ;;
-	-c|--container)
-	    CONTAINER="$2"
-	    shift
-	    shift
-	    ;;
-	-d|--debug)
-	    debug=1
-	    shift
-	    ;;
-	-i|--image)
-	    IMAGE="$2"
-	    shift # past argument
-	    shift # past value
-	    ;;
-	-n|--no)
-	    run_flag=0
-	    shift
-	    ;;
-	-r|--rm)
-	    REMOVE="--rm"
-	    shift # past argument
-	    ;;
-	-v|--volume)
-	    VOLUME_ARGS="$VOLUME_ARGS -v $2"
-	    shift # past argument
-	    shift # past value
-	    ;;
-	--)
-	    shift # past --
-	    break
-	    ;;
-	*)    # unknown option
-	    echo "Unknown option '$key' (Did you forget the --)"
-	    print_help
-	    exit 1
-	    ;;
+    -a|--argfile)
+        ARG_FILE="$2"
+        shift # past argument
+        shift # past value
+        ;;
+    -h|--help)
+        print_help
+        exit 0
+        ;;
+    -c|--container)
+        CONTAINER="$2"
+        shift
+        shift
+        ;;
+    -d|--debug)
+        debug=1
+        shift
+        ;;
+    -i|--image)
+        IMAGE="$2"
+        shift # past argument
+        shift # past value
+        ;;
+    -n|--no)
+        run_flag=0
+        shift
+        ;;
+    -r|--rm)
+        REMOVE="--rm"
+        shift # past argument
+        ;;
+    -v|--volume)
+        VOLUME_ARGS="$VOLUME_ARGS -v $2"
+        shift # past argument
+        shift # past value
+        ;;
+    --)
+        shift # past --
+        break
+        ;;
+    *)    # unknown option
+        echo "Unknown option '$key' (Did you forget the --)"
+        print_help
+        exit 1
+        ;;
     esac
 done
 
@@ -186,23 +186,23 @@ fi
 if [[ -r "$ARG_FILE" ]]; then
     while read -r line
     do
-	case $line in
-	    *#*)
-		# Comment, do nothing
-		;;
-	    --*)
-		# Raw options
-		RAW_ARGS="$RAW_ARGS $line"
-		;;
-	    *:*)
-		# Volume mapping
- 		VOLUME_ARGS="$VOLUME_ARGS -v $line"		
-		;;
-	    *=*)
-		# Environment variable
-		ENV_ARGS="$ENV_ARGS -e $line"
-		;;
-	esac    
+    case $line in
+        *#*)
+        # Comment, do nothing
+        ;;
+        --*)
+        # Raw options
+        RAW_ARGS="$RAW_ARGS $line"
+        ;;
+        *:*)
+        # Volume mapping
+        VOLUME_ARGS="$VOLUME_ARGS -v $line"     
+        ;;
+        *=*)
+        # Environment variable
+        ENV_ARGS="$ENV_ARGS -e $line"
+        ;;
+    esac    
     done < $ARG_FILE
 fi
 
@@ -227,7 +227,7 @@ fi
 container_status "$CONTAINER" status
 print_msg $debug "status: $status"
 
-cid="${status%:*}"	 # everything before the :
+cid="${status%:*}"   # everything before the :
 cstatus="${status##*:}"  # everything after the :
 cstatus="${cstatus%% *}" # Only keep the first word
 
@@ -245,32 +245,32 @@ docker_volume_opts=""
 
 case "$cstatus" in
     Up)
-	print_msg $debug "Container is up and running"
-	run_cmd $debug $run_flag docker exec $docker_exec_opts $CONTAINER $command "$@"
-	;;
+    print_msg $debug "Container is up and running"
+    run_cmd $debug $run_flag docker exec $docker_exec_opts $CONTAINER $command "$@"
+    ;;
     Exited)
-	print_msg $debug "Container exited. Restarting it"
-	run_cmd $debug $run_flag docker start "$CONTAINER"
-	run_cmd $debug $run_flag docker exec $docker_exec_opts $CONTAINER $command "$@"
-	;;
+    print_msg $debug "Container exited. Restarting it"
+    run_cmd $debug $run_flag docker start "$CONTAINER"
+    run_cmd $debug $run_flag docker exec $docker_exec_opts $CONTAINER $command "$@"
+    ;;
     Created)
-	echo "Removing existing container '$CONTAINER' that failed to run..."
-	docker rm "$CONTAINER"
-	print_msg $debug "Starting container"
-	run_cmd $debug $run_flag \
-		docker run $REMOVE $VOLUME_ARGS $docker_display_opts \
-		$docker_run_opts $IMAGE $command "$@"
-	;;
+    echo "Removing existing container '$CONTAINER' that failed to run..."
+    docker rm "$CONTAINER"
+    print_msg $debug "Starting container"
+    run_cmd $debug $run_flag \
+        docker run $REMOVE $VOLUME_ARGS $docker_display_opts \
+        $docker_run_opts $IMAGE $command "$@"
+    ;;
     *)
-	if [ ! -z "$cstatus" ]; then
-	    echo "Container '$CONTAINER' status not recognized '$cstatus'"
-	    exit 1
-	fi
-	print_msg $debug "Container doesn't exist. Starting one"
-	run_cmd $debug $run_flag \
-		docker run $REMOVE $VOLUME_ARGS $docker_display_opts \
-		$docker_run_opts $IMAGE $command "$@"
-	;;
+    if [ ! -z "$cstatus" ]; then
+        echo "Container '$CONTAINER' status not recognized '$cstatus'"
+        exit 1
+    fi
+    print_msg $debug "Container doesn't exist. Starting one"
+    run_cmd $debug $run_flag \
+        docker run $REMOVE $VOLUME_ARGS $docker_display_opts -e "LD_LIBRARY_PATH=/usr/local/lrose/lib" \
+        $docker_run_opts $IMAGE $command "$@"
+    ;;
 esac
 
 exit 0
